<a href="https://colab.research.google.com/github/claredavies/ArtificialIntelligience/blob/main/ComputationalIntelligienceAssignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import numpy
import pandas as pd
import random

"""
The y=target is to maximize this equation ASAP:
    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best possible values after a number of generations.
"""


'\nThe y=target is to maximize this equation ASAP:\n    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6\n    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)\n    What are the best values for the 6 weights w1 to w6?\n    We are going to use the genetic algorithm for the best possible values after a number of generations.\n'

In [2]:
# genetic algorithm search of the one max optimization problem
from numpy.random import randint
from numpy.random import rand

# Functions

In [4]:
def mutation(offspring_crossover):
    # Mutation changes a single gene in each offspring randomly.
    for idx in range(offspring_crossover.shape[0]):
        # The random value to be added to the gene.
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

# Genetic Algorithm

In [5]:
# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = 6

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""

sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.

#Creating the initial population.
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

[[ 1.23145515  0.08330008  2.40681208  3.47293174 -1.73410159 -1.75130758]
 [-2.33322084 -1.17689238 -1.26356183 -1.24069434 -3.38813149 -3.55575632]
 [ 3.99451765  1.77643799  2.29347156  0.93170323  2.87812932  1.38458766]
 [-2.6973714   2.89210477 -3.65602294 -0.64348941 -1.05049031 -2.29093071]
 [ 3.30855161 -3.75580175  2.99310197 -0.78911688  3.4498672  -0.0634816 ]
 [-0.5919176   3.92421876 -1.29219629 -0.66768244  0.56349707 -0.04836104]
 [ 2.41652492 -0.78475898  1.21769088  0.40499584 -3.47510427 -1.63715361]
 [ 0.77352929 -2.86400888  3.9365859  -1.93601106 -2.03262492 -3.43941558]]


In [6]:
def evolutionary_algorithm(num_generations):
  for generation in range(num_generations):
      print("Generation : ", generation)
      # Measing the fitness of each chromosome in the population.
      fitness = cal_pop_fitness(equation_inputs, new_population)

      # Selecting the best parents in the population for mating.
      parents = select_mating_pool(new_population, fitness, 
                                        num_parents_mating)

      # Generating next generation using crossover.
      offspring_crossover = crossover(parents,
                                        offspring_size=(pop_size[0]-parents.shape[0], num_weights))

      # Adding some variations to the offsrping using mutation.
      offspring_mutation = mutation(offspring_crossover)

      # Creating the new population based on the parents and offspring.
      new_population[0:parents.shape[0], :] = parents
      new_population[parents.shape[0]:, :] = offspring_mutation

      # The best result in the current iteration.
      print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

  # Getting the best solution after iterating finishing all generations.
  #At first, the fitness is calculated for each solution in the final generation.
  fitness = cal_pop_fitness(equation_inputs, new_population)
  # Then return the index of that solution corresponding to the best fitness.
  best_match_idx = numpy.where(fitness == numpy.max(fitness))

  print("Finished Iterations")
  print("Best solution : ", new_population[best_match_idx, :])
  print("Best solution fitness : ", fitness[best_match_idx])

  return new_population[best_match_idx, :]

# Inputs

Class Info

In [7]:
#Creating Series
class_series = pd.Series(['Class1', 'Class1', 'Class1', 'Class1','Class2', 'Class2', 'Class2', 'Class2'])
subject_series = pd.Series(['Maths', 'English', 'Chemistry', 'History','Maths', 'English', 'History', 'Physics'])
hours_series = pd.Series([3, 4, 5, 3, 2, 4, 5, 3])


#Creating Dictionary
frame = { 'Class': class_series, 'Subject': subject_series, 'Hours': hours_series }
#Creating Dataframe
class_subject_hours_dataframe = pd.DataFrame(frame)

#Printing dataframe
print(class_subject_hours_dataframe)

    Class    Subject  Hours
0  Class1      Maths      3
1  Class1    English      4
2  Class1  Chemistry      5
3  Class1    History      3
4  Class2      Maths      2
5  Class2    English      4
6  Class2    History      5
7  Class2    Physics      3


Teacher Info

In [8]:
teacher_series = pd.Series(['ProfessorA', 'ProfessorA', 'ProfessorB', 'ProfessorB','ProfessorC', 'ProfessorC'])
subject_series = pd.Series(['Maths', 'English', 'Chemistry', 'History','Maths', 'Physics'])

#Creating Dictionary
frame = { 'Teacher': teacher_series, 'Subject': subject_series}
#Creating Dataframe
teacher_subject_dataframe = pd.DataFrame(frame)

teacher_subject_array = teacher_subject_dataframe.to_numpy()
#Printing dataframe
print(teacher_subject_array)

[['ProfessorA' 'Maths']
 ['ProfessorA' 'English']
 ['ProfessorB' 'Chemistry']
 ['ProfessorB' 'History']
 ['ProfessorC' 'Maths']
 ['ProfessorC' 'Physics']]


Define Timetable

In [9]:
startTime = 10
durationLesson = 1
lunchTime = 12
durationLunch = 1
endTime = 15

singleTimetable = []
daysOfWeek = ['Mon','Tue','Wed', 'Thur']

for day in daysOfWeek:
  for time in range(startTime, endTime, durationLesson):
    if time != lunchTime:
      singleTimetable.append([day, time])

print(singleTimetable)

[['Mon', 10], ['Mon', 11], ['Mon', 13], ['Mon', 14], ['Tue', 10], ['Tue', 11], ['Tue', 13], ['Tue', 14], ['Wed', 10], ['Wed', 11], ['Wed', 13], ['Wed', 14], ['Thur', 10], ['Thur', 11], ['Thur', 13], ['Thur', 14]]


In [10]:
def create_timetables(class_subject_hours_dataframe, timetable):
  all_timetables = []
  blank_timetable = [None] * len(timetable)
  number_class_timetables = class_subject_hours_dataframe.Class.nunique()

  for x in range(number_class_timetables):
    all_timetables.append(blank_timetable)

  # print(all_timetables)
  all_timetables_array = numpy.array(all_timetables)
  return all_timetables_array

In [11]:
def make_array_1_hour_class(class_mask):
  list_classes_1hr = []
  for index, row in class_mask.iterrows():
    number_hours_per_class = row['Hours']
    for x in range(number_hours_per_class):
      list_classes_1hr.append(row['Subject'])
  list_finished = list_classes_1hr.copy()
  return list_finished

# Genetic Fucntions Timetable

In [12]:
def generate_intial_population(class_subject_hours_dataframe, teacher_subject_dataframe, timetable, populationSize):
  population = []
  class_names = class_subject_hours_dataframe.Class.unique()
  number_class_names = class_subject_hours_dataframe.Class.nunique()

  for a in range(populationSize):
    trackClass = 0
    all_timetables = create_timetables(class_subject_hours_dataframe, timetable)
    for class_name in class_names:
      mask = class_subject_hours_dataframe.loc[class_subject_hours_dataframe['Class'] == class_name]
      list_classes_1hr = make_array_1_hour_class(mask)
      list_indices_single_timetable = [None] * len(timetable)

      if(len(list_classes_1hr) > len(list_indices_single_timetable) ):
        print("Not enough hours in timetable for class hours set!!")
        return

      for i in range(len(list_indices_single_timetable)):
        list_indices_single_timetable[i] = i
    
      range_end_single_timetable = len(list_indices_single_timetable) - 1

      for j in range((len(list_classes_1hr) - 1)):
        random_num = random.randint(0, range_end_single_timetable)

        random_num_index_value = list_indices_single_timetable[random_num]
        all_timetables[trackClass][random_num_index_value] = list_classes_1hr[j]
    
        list_indices_single_timetable.pop(random_num)
        range_end_single_timetable = range_end_single_timetable - 1
    
      trackClass = trackClass + 1

    population.append(all_timetables)
  return population

In [13]:
def fitnessFunction(pop):
  arrPop = numpy.array(pop)
  num_representations = arrPop.shape[0]
  NoClashesList = [None] * num_representations
 
  print("no representations:  " + str(num_representations))
  for i in range(num_representations):
    populationSelect = pop[i]
    noClashes = calClashes(populationSelect)
    NoClashesList[i] = noClashes

  return NoClashesList

In [14]:
def calClashes(pop):
  num_timetable_slots = pop.shape[1]
  num_classes = pop.shape[0]

  clash = 0
  for i in range(num_timetable_slots):
    for j in range(1, num_classes):
      if(pop[(j-1)][i] == pop[j][i]):
        if(pop[(j-1)][i] != None):
          clash = clash + 1

  return clash

In [35]:
def recombine(parent1, parent2):
  parent1Array = numpy.array(parent1)
  parent2Array = numpy.array(parent2)

  recombinationResults = []

  noTimetables = parent2Array.shape[0]
  crossOverIndex = int(parent1Array.shape[1]/2)

  recombinedParent1Array = parent1Array.copy()
  recombinedParent2Array = parent2Array.copy()

  for i in range(noTimetables): 
    classRecombinationResults = []  
    parent1FirstHalf = parent1Array[i][0:(crossOverIndex-1)]
    parent1SecondHalf = parent1Array[i][(crossOverIndex-1):(parent1.shape[1])]
    parent2FirstHalf = parent2Array[i][0:(crossOverIndex-1)]
    parent2SecondHalf = parent2Array[i][(crossOverIndex-1):(parent2.shape[1])]

    indicesListNotMatching1stParent = []
    indicesListNotMatching2ndParent = []
    length2ndHalf = len(parent2SecondHalf)

    parent1OriginalSecondHalfCopy = parent1SecondHalf.copy()
    parent1ResultSecondHalf = parent2SecondHalf.copy()

    parent2OriginalSecondHalfCopy = parent2SecondHalf.copy()
    parent2ResultSecondHalf = parent1SecondHalf.copy()

    for j in range(length2ndHalf):
      if parent1ResultSecondHalf[j] not in parent1OriginalSecondHalfCopy:
        indicesListNotMatching1stParent.append(j)
      else:
        resultParent1 = numpy.where(parent1OriginalSecondHalfCopy == parent1ResultSecondHalf[j])
        parent1OriginalSecondHalfCopy = numpy.delete(parent1OriginalSecondHalfCopy, resultParent1[0][0])

    for k in range(len(parent1OriginalSecondHalfCopy)):
      parent1ResultSecondHalf[indicesListNotMatching1stParent[k]] = parent1OriginalSecondHalfCopy[k]

    for l in range(length2ndHalf):
      if parent2ResultSecondHalf[l] not in parent2OriginalSecondHalfCopy:
        indicesListNotMatching2ndParent.append(l)
      else:
        resultParent2 = numpy.where(parent2OriginalSecondHalfCopy == parent2ResultSecondHalf[l])
        parent2OriginalSecondHalfCopy = numpy.delete(parent2OriginalSecondHalfCopy, resultParent2[0][0])

    for m in range(len(parent2OriginalSecondHalfCopy)):
      parent2ResultSecondHalf[indicesListNotMatching2ndParent[m]] = parent2OriginalSecondHalfCopy[m]

    recombinedParent1 = numpy.concatenate((parent1FirstHalf, parent1ResultSecondHalf))
    recombinedParent2 = numpy.concatenate((parent2FirstHalf, parent2ResultSecondHalf))

    recombinedParent1Array[i] = recombinedParent1
    recombinedParent2Array[i] = recombinedParent2

  recombinationResults.append(recombinedParent1Array)
  recombinationResults.append(recombinedParent2Array)

  return recombinationResults

In [54]:
def mutation(recombinationResults):
  randGen = random.randint(0, 5)
  if randGen > 3:
    print("Mutation")
    randStartInd = random.randint(0, len(recombinationResults[0][0]))
    randEndInd = random.randint(0, len(recombinationResults[0][0]))
    
    for i in range(len(recombinationResults[0])):
      startIndexValueParent1 = recombinationResults[0][i][randStartInd]
      recombinationResults[0][i][randStartInd] = recombinationResults[0][i][randEndInd]
      recombinationResults[0][i][randEndInd] = startIndexValueParent1

      startIndexValueParent2 = recombinationResults[1][i][randStartInd]
      recombinationResults[1][i][randStartInd] = recombinationResults[1][i][randEndInd]
      recombinationResults[1][i][randEndInd] = recombinationResults[1][i][randStartInd]

  return recombinationResults

In [56]:
def evolutionary_algo(class_subject_hours_dataframe, teacher_subject_dataframe, singleTimetable, intialPopultationSize):
  population = generate_intial_population(class_subject_hours_dataframe, teacher_subject_dataframe, singleTimetable, intialPopultationSize)
  fitness = fitnessFunction(population)

  min_value = min(fitness)
  min_index = fitness.index(min_value)
  fitnessWithoutMin = fitness.copy()
  fitnessWithoutMin[min_index] = 1000
  second_min_value = min(fitnessWithoutMin)
  second_min_index = fitness.index(second_min_value)

  firstParent = population[min_index]
  secondParent =  population[second_min_index]

  print("Parent 1:  " + str(firstParent))
  print("Parent 2:  " + str(secondParent))

  recombinationParentResults = recombine(firstParent, secondParent)
  print("Recombination results:  " + str(recombinationParentResults))

  recombinationParentResultsMutation = mutation(recombinationParentResults)
  print("Mutation results:  " + str(recombinationParentResultsMutation))

  # Creating the new population based on the parents and offspring.
      # new_population[0:parents.shape[0], :] = parents
      # new_population[parents.shape[0]:, :] = offspring_mutation

In [57]:
evolutionary_algo(class_subject_hours_dataframe, teacher_subject_dataframe, singleTimetable, 4)

no representations:  4
Parent 1:  [['Chemistry' 'Maths' 'Maths' None 'Chemistry' 'History' 'English'
  'Chemistry' 'Chemistry' 'Maths' 'Chemistry' 'English' 'English' None
  'History' 'English']
 [None 'History' 'Physics' 'English' 'Maths' None 'History' 'History'
  None 'History' 'History' 'English' 'Maths' 'English' 'English'
  'Physics']]
Parent 2:  [['History' 'Maths' 'English' 'Maths' None 'English' 'Chemistry'
  'English' 'Chemistry' 'Chemistry' 'English' 'Chemistry' 'Chemistry'
  'History' 'Maths' None]
 [None 'History' 'English' None 'English' 'English' 'History' 'Maths'
  'Maths' 'History' 'History' 'English' None 'Physics' 'Physics'
  'History']]
Recombination results:  [array([['Chemistry', 'Maths', 'Maths', None, 'Chemistry', 'History',
        'English', 'English', 'Chemistry', 'Chemistry', 'English',
        'Chemistry', 'English', 'History', 'Maths', None],
       [None, 'History', 'Physics', 'English', 'Maths', None, 'History',
        'Maths', 'English', 'History', 'Hi

# Execution

In [38]:
num_generations = 5

evolutionary_algorithm(num_generations)

Generation :  0
Best result :  134.30444802581837
Generation :  1
Best result :  134.30444802581837
Generation :  2
Best result :  138.95503532987385
Generation :  3
Best result :  142.72556515422528
Generation :  4
Best result :  150.93878864210043
Finished Iterations
Best solution :  [[[ -1.62969513  -2.97072974   2.30087151   2.18980049 -10.44629408
    -3.74570684]]]
Best solution fitness :  [150.93878864]


array([[[ -1.62969513,  -2.97072974,   2.30087151,   2.18980049,
         -10.44629408,  -3.74570684]]])