<a href="https://colab.research.google.com/github/claredavies/ArtificialIntelligience/blob/main/ComputationalIntelligienceAssignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [1]:
import numpy
import pandas as pd
import random

"""
The y=target is to maximize this equation ASAP:
    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6
    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)
    What are the best values for the 6 weights w1 to w6?
    We are going to use the genetic algorithm for the best possible values after a number of generations.
"""


'\nThe y=target is to maximize this equation ASAP:\n    y = w1x1+w2x2+w3x3+w4x4+w5x5+6wx6\n    where (x1,x2,x3,x4,x5,x6)=(4,-2,3.5,5,-11,-4.7)\n    What are the best values for the 6 weights w1 to w6?\n    We are going to use the genetic algorithm for the best possible values after a number of generations.\n'

In [2]:
# genetic algorithm search of the one max optimization problem
from numpy.random import randint
from numpy.random import rand

# Functions

In [3]:
def cal_pop_fitness(equation_inputs, pop):
    # Calculating the fitness value of each solution in the current population.
    # The fitness function caulcuates the sum of products between each input and its corresponding weight.
    fitness = numpy.sum(pop*equation_inputs, axis=1)
    return fitness

In [4]:
def select_mating_pool(pop, fitness, num_parents):
    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.
    parents = numpy.empty((num_parents, pop.shape[1]))
    for parent_num in range(num_parents):
        max_fitness_idx = numpy.where(fitness == numpy.max(fitness))
        max_fitness_idx = max_fitness_idx[0][0]
        parents[parent_num, :] = pop[max_fitness_idx, :]
        fitness[max_fitness_idx] = -99999999999
    return parents

In [5]:
def crossover(parents, offspring_size):
    offspring = numpy.empty(offspring_size)
    # The point at which crossover takes place between two parents. Usually it is at the center.
    crossover_point = numpy.uint8(offspring_size[1]/2)
    for k in range(offspring_size[0]):
        # Index of the first parent to mate.
        parent1_idx = k%parents.shape[0]
        # Index of the second parent to mate.
        parent2_idx = (k+1)%parents.shape[0]
        # The new offspring will have its first half of its genes taken from the first parent.
        offspring[k, 0:crossover_point] = parents[parent1_idx, 0:crossover_point]
        # The new offspring will have its second half of its genes taken from the second parent.
        offspring[k, crossover_point:] = parents[parent2_idx, crossover_point:]
    return offspring

In [6]:
def mutation(offspring_crossover):
    # Mutation changes a single gene in each offspring randomly.
    for idx in range(offspring_crossover.shape[0]):
        # The random value to be added to the gene.
        random_value = numpy.random.uniform(-1.0, 1.0, 1)
        offspring_crossover[idx, 4] = offspring_crossover[idx, 4] + random_value
    return offspring_crossover

# Genetic Algorithm

In [7]:
# Inputs of the equation.
equation_inputs = [4,-2,3.5,5,-11,-4.7]

# Number of the weights we are looking to optimize.
num_weights = 6

"""
Genetic algorithm parameters:
    Mating pool size
    Population size
"""

sol_per_pop = 8
num_parents_mating = 4

# Defining the population size.
pop_size = (sol_per_pop,num_weights) # The population will have sol_per_pop chromosome where each chromosome has num_weights genes.

#Creating the initial population.
new_population = numpy.random.uniform(low=-4.0, high=4.0, size=pop_size)
print(new_population)

[[-3.07755121 -1.15218959 -3.09198927  1.56016492  2.93286405 -2.63164444]
 [-3.92407848 -0.57477096 -0.17982241 -1.74551137 -0.44493719 -2.20722075]
 [ 3.74589958  1.28143012 -3.35331461 -2.66043445  2.81726544  1.65176607]
 [-1.934991    1.75724524 -2.69190067  0.65703143  3.31507433  0.13270122]
 [ 2.96290152 -0.23718798 -3.85767334 -0.0079308   0.48277099  1.95335724]
 [-2.63731583  1.4145668   2.31945949 -2.4656567  -1.33325376  0.35072146]
 [ 3.47803198 -2.84049944  0.3258693   2.27388744 -0.97436805 -1.52546197]
 [-2.88577089 -2.00506123  0.86320134 -0.36559671  3.41421058 -2.66813887]]


In [8]:
def evolutionary_algorithm(num_generations):
  for generation in range(num_generations):
      print("Generation : ", generation)
      # Measing the fitness of each chromosome in the population.
      fitness = cal_pop_fitness(equation_inputs, new_population)

      # Selecting the best parents in the population for mating.
      parents = select_mating_pool(new_population, fitness, 
                                        num_parents_mating)

      # Generating next generation using crossover.
      offspring_crossover = crossover(parents,
                                        offspring_size=(pop_size[0]-parents.shape[0], num_weights))

      # Adding some variations to the offsrping using mutation.
      offspring_mutation = mutation(offspring_crossover)

      # Creating the new population based on the parents and offspring.
      new_population[0:parents.shape[0], :] = parents
      new_population[parents.shape[0]:, :] = offspring_mutation

      # The best result in the current iteration.
      print("Best result : ", numpy.max(numpy.sum(new_population*equation_inputs, axis=1)))

  # Getting the best solution after iterating finishing all generations.
  #At first, the fitness is calculated for each solution in the final generation.
  fitness = cal_pop_fitness(equation_inputs, new_population)
  # Then return the index of that solution corresponding to the best fitness.
  best_match_idx = numpy.where(fitness == numpy.max(fitness))

  print("Finished Iterations")
  print("Best solution : ", new_population[best_match_idx, :])
  print("Best solution fitness : ", fitness[best_match_idx])

  return new_population[best_match_idx, :]

# Inputs

Class Info

In [9]:
#Creating Series
class_series = pd.Series(['Class1', 'Class1', 'Class1', 'Class1','Class2', 'Class2', 'Class2', 'Class2'])
subject_series = pd.Series(['Maths', 'English', 'Chemistry', 'History','Maths', 'English', 'History', 'Physics'])
hours_series = pd.Series([3, 4, 5, 3, 2, 4, 5, 3])


#Creating Dictionary
frame = { 'Class': class_series, 'Subject': subject_series, 'Hours': hours_series }
#Creating Dataframe
class_subject_hours_dataframe = pd.DataFrame(frame)

#Printing dataframe
print(class_subject_hours_dataframe)

    Class    Subject  Hours
0  Class1      Maths      3
1  Class1    English      4
2  Class1  Chemistry      5
3  Class1    History      3
4  Class2      Maths      2
5  Class2    English      4
6  Class2    History      5
7  Class2    Physics      3


Teacher Info

In [10]:
teacher_series = pd.Series(['ProfessorA', 'ProfessorA', 'ProfessorB', 'ProfessorB','ProfessorC', 'ProfessorC'])
subject_series = pd.Series(['Maths', 'English', 'Chemistry', 'History','Maths', 'Physics'])

#Creating Dictionary
frame = { 'Teacher': teacher_series, 'Subject': subject_series}
#Creating Dataframe
teacher_subject_dataframe = pd.DataFrame(frame)

teacher_subject_array = teacher_subject_dataframe.to_numpy()
#Printing dataframe
print(teacher_subject_array)

[['ProfessorA' 'Maths']
 ['ProfessorA' 'English']
 ['ProfessorB' 'Chemistry']
 ['ProfessorB' 'History']
 ['ProfessorC' 'Maths']
 ['ProfessorC' 'Physics']]


Define Timetable

In [11]:
startTime = 10
durationLesson = 1
lunchTime = 12
durationLunch = 1
endTime = 15

singleTimetable = []
daysOfWeek = ['Mon','Tue','Wed', 'Thur']

for day in daysOfWeek:
  for time in range(startTime, endTime, durationLesson):
    if time != lunchTime:
      singleTimetable.append([day, time])

print(singleTimetable)

[['Mon', 10], ['Mon', 11], ['Mon', 13], ['Mon', 14], ['Tue', 10], ['Tue', 11], ['Tue', 13], ['Tue', 14], ['Wed', 10], ['Wed', 11], ['Wed', 13], ['Wed', 14], ['Thur', 10], ['Thur', 11], ['Thur', 13], ['Thur', 14]]


In [43]:
def create_timetables(class_subject_hours_dataframe, timetable):
  all_timetables = []
  blank_timetable = [None] * len(timetable)
  number_class_timetables = class_subject_hours_dataframe.Class.nunique()

  for x in range(number_class_timetables):
    all_timetables.append(blank_timetable)

  # print(all_timetables)
  all_timetables_array = numpy.array(all_timetables)
  return all_timetables_array

In [13]:
def make_array_1_hour_class(class_mask):
  list_classes_1hr = []
  for index, row in class_mask.iterrows():
    number_hours_per_class = row['Hours']
    for x in range(number_hours_per_class):
      list_classes_1hr.append(row['Subject'])
  list_finished = list_classes_1hr.copy()
  return list_finished

In [80]:
def generate_intial_population(class_subject_hours_dataframe, teacher_subject_dataframe, timetable, populationSize):
  all_timetables = create_timetables(class_subject_hours_dataframe, timetable)
  class_names = class_subject_hours_dataframe.Class.unique()
  number_class_names = class_subject_hours_dataframe.Class.nunique()

  trackClass = 0

  for class_name in class_names:
    mask = class_subject_hours_dataframe.loc[class_subject_hours_dataframe['Class'] == class_name]
    list_classes_1hr = make_array_1_hour_class(mask)
    
    list_indices_single_timetable = [None] * len(timetable)
    for i in range(len(list_indices_single_timetable)):
      list_indices_single_timetable[i] = i
   
    # print(list_indices_single_timetable)

    range_end_single_timetable = len(list_indices_single_timetable) - 1

    for j in range((len(list_classes_1hr) - 1)):
      random_num = random.randint(0, range_end_single_timetable)
      # print("list_classes_1hr " + str(list_classes_1hr))
      # print("j (position): " + str(j))
      # print("random number: " + str(random_num))

      random_num_index_value = list_indices_single_timetable[random_num]
      # print("value of random number index (in timetable): " + str(random_num_index_value))
      # print("list_indices_single_timetable :  " + str(list_indices_single_timetable))

      # print(all_timetables[trackClass][random_num_index_value])
      # print(list_classes_1hr[j])
      all_timetables[trackClass][random_num_index_value] = list_classes_1hr[j]
  
      list_indices_single_timetable.pop(random_num)
      range_end_single_timetable = range_end_single_timetable - 1

      # print("list_indices_single_timetable: " + str(list_indices_single_timetable))


      print(all_timetables)
  
    trackClass = trackClass + 1

In [81]:
generate_intial_population(class_subject_hours_dataframe, teacher_subject_dataframe, singleTimetable, 4)

list_classes_1hr ['Maths', 'Maths', 'Maths', 'English', 'English', 'English', 'English', 'Chemistry', 'Chemistry', 'Chemistry', 'Chemistry', 'Chemistry', 'History', 'History', 'History']
j (position): 0
random number: 4
value of random number index (in timetable): 4
list_indices_single_timetable :  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
None
Maths
[[None None None None 'Maths' None None None None None None None None
  None None None]
 [None None None None None None None None None None None None None None
  None None]]
list_classes_1hr ['Maths', 'Maths', 'Maths', 'English', 'English', 'English', 'English', 'Chemistry', 'Chemistry', 'Chemistry', 'Chemistry', 'Chemistry', 'History', 'History', 'History']
j (position): 1
random number: 13
value of random number index (in timetable): 14
list_indices_single_timetable :  [0, 1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
None
Maths
[[None None None None 'Maths' None None None None None None None None
  None 'Maths' None]
 [No

# Execution

In [38]:
num_generations = 5

evolutionary_algorithm(num_generations)

Generation :  0
Best result :  134.30444802581837
Generation :  1
Best result :  134.30444802581837
Generation :  2
Best result :  138.95503532987385
Generation :  3
Best result :  142.72556515422528
Generation :  4
Best result :  150.93878864210043
Finished Iterations
Best solution :  [[[ -1.62969513  -2.97072974   2.30087151   2.18980049 -10.44629408
    -3.74570684]]]
Best solution fitness :  [150.93878864]


array([[[ -1.62969513,  -2.97072974,   2.30087151,   2.18980049,
         -10.44629408,  -3.74570684]]])